### ISSUE TITLE
[feature request] Custom Colors: base and outline

### ISSUE THREAD

**Issue by SeraphyBR** [ful1e5/Bibata_Cursor#104]
It would be nice if I could do a build of the theme informing custom colors for the Base and Outline, easily passing parameters to make, without having to edit the code directly in https://github.com/ful1e5/Bibata_Cursor/blob/main/bitmapper/packages/modern/src/config.ts.

**Comment by SeraphyBR** [comment]
Now talking about it, I don't understand why having other repositories like Bibata_Extra_Cursor, if it has other differences in relation to the main one

**Comment by ful1e5** [comment]
> Now talking about this I don't understand why having other repositories like Bibata_Extra_Cursor, I don't know if it has any other differences compared to the main one

No. There is no difference between this and Bibata_Extra now. 

Before the custom colors are not implemented inside Bibata_Cursor, Bibata_Extra is a go-through where Bibata is found with extra colors.  

I came up with this idea for making this repo packages less bloat.

**Comment by ful1e5** [comment]
Check [README.md#customize-colors](https://github.com/ful1e5/Bibata_Cursor#customize-colors).
