### ISSUE TITLE
[Modern Classic] I-Beam cursor is blurry

### ISSUE THREAD

**Issue by ExposedCat** [ful1e5/Bibata_Cursor#117]
## Description of the problem
Modern Classic I-Beam (on text hover) cursor is blurry, while all the others look good

## How has this issue affected you? What are you trying to accomplish?
It's expected to be consistent with others, but now it looks completely different and feels blurry

### Logs or Screenshots: (optional)

![image](https://user-images.githubusercontent.com/44642024/181825313-6d31c21f-9c40-4e6d-aca1-9623ce20f7ed.png)
This is ok:
![image](https://user-images.githubusercontent.com/44642024/181826238-1c193234-d04e-40d5-bec6-998a56666b00.png)
![image](https://user-images.githubusercontent.com/44642024/181826295-3cef40ba-b121-45d2-b69b-994ea9ab81a4.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Operating System | Linux Fedora Workstation 35 |
| Theme | 1.1.2 |

**Comment by ful1e5** [comment]
@ExposedCat Which cursor size are you using?
