### ISSUE TITLE
Outline/shadow artifacts

### ISSUE THREAD

**Issue by crabvk** [ful1e5/Bibata_Cursor#118]
Hello.
I've just updated to the latest release and have strange artifacts on cursors.
![20221003_19h23m53s_grim](https://user-images.githubusercontent.com/3273827/193604393-a50e9cfc-0ca9-4657-aa6e-bb23f1ee732e.png)

**Bibata Cursor:** 2.0.0
**OS:** ArchLinux 5.19.12
**WM:** Sway 1.7

Tried both, building from source and prebuilt version.
Didn't have the problem before 2.0.0

**Comment by ful1e5** [comment]
I encountered this issue while testing Bibata 2.0.0 but it doesn't occur when using it in KDE but shows up in the preview.
Which sounds like yours.
![image](https://user-images.githubusercontent.com/24286590/193729854-02df57da-f9c2-47b6-8692-b20ce049d47a.png)
I have assigned myself to this bug. Hopefully, I will fix this bug as soon as possible.

**Comment by rrjoaofrancisco** [comment]
Hello. 
Same problem here.

Bibata Cursor: 2.0.0
OS: Fedora 36
Gnome 42.4
WS: X11

**Comment by joos2k** [comment]
Same problem here, but Adwaita is also affected. (as you can see in your screenshot @ful1e5 )
OS: Arch, KDE
Maybe the root cause is something else and not this cursor theme.

**Comment by crabvk** [comment]
@joos2k
But then Bibata v1.1.2 doesn't have such an issue.
And that Text Pointer/I-beam cursor on the screenshot, it's not Adwaita's, looks exactly like Bibata's one. Maybe some bug in KDE cursors preview app.

**Comment by joos2k** [comment]
@crabvk Yes, you are right, but it is not only in the preview. If I apply Adwaita, then the I-beam is ruffled too.
Another thing: Bibata Modern and Original Ice are affected in the preview but not when the theme is applied. At least on my system. Very strange.

**Comment by travisghansen** [comment]
I have exactly the same issue using arch (amd graphics, gnome DE). Strange artifacts in different scenarios as the others have described (seemingly sporadic in some cases). No issues at all with the previous versions.

**Comment by ful1e5** [comment]
Look like the problem is caused by the cursors builder [clickgen](https://github.com/ful1e5/clickgen). I patched the bug inside the builder and will release new version soon. 
Thanks for reporting.

**Comment by crabvk** [comment]
Thank you.
I confirm that the issue is no longer present.

**Comment by ful1e5** [comment]
Fixed in Bibata `v2.0.1`
