### ISSUE TITLE
Any chance of distributing 16x16 sizes for Linux (as in Windows)?

### ISSUE THREAD

**Issue by vaskark** [ful1e5/Bibata_Cursor#129]
See title.

**Comment by ful1e5** [comment]
I will first try to fix the bugs in this theme and reduce the amount of storage space needed. This is because adding new pixel sizes will increase the overall storage space of the final binary package. I hope that the pixel size of XCursor will be increased in the new version.

**Comment by pawanyadav** [comment]
build from source (x11) removed extra size keeping only 16-32 and size is 6 mb only, default one was over 50 mb
