### ISSUE TITLE
Just an FYI

### ISSUE THREAD

**Issue by yochananmarqos** [ful1e5/Bibata_Cursor#131]
I've just made Bibata-Modern-Classic the default cursor theme on Manjaro GNOME and Bibata-Modern-Ice the default on Manjaro Cinnamon. Both `bibata-cursor-theme` and `python-clickgen` are now in the Manjaro community repository.

Thanks for making my favorite cursor theme and keep up the good work! :+1:

**Comment by Salamandar** [comment]
Yes, that just added 450Mo to my installation without asking me, thanks…

**Comment by Salamandar** [comment]
OK… I'll stop complaining then :D 40MiB is way more acceptable. Thanks for the hard work !

**Comment by yochananmarqos** [comment]
On that note I'll close this since it's not a real issue and @ful1e5 has been informed.
