### ISSUE TITLE
Installation from Arch extra repo

### ISSUE THREAD

**Issue by Solarunit** [ful1e5/Bibata_Cursor#141]
Hi, could you add Bibata cursors to the Arch extra repo?
Yes, I saw an AUR option, but I think it would be nice to have it in extra repo.

**Comment by trueNAHO** [comment]
Only [Trusted Users](https://wiki.archlinux.org/title/Trusted_Users) and Arch Developers maintain the *extra* repo:

> ### extra 
> 
> This repository can be found in `.../extra/os/` on your favorite mirror.
> 
> *extra* contains all packages that do not fit in *core*. This repository is jointly maintained by the [Trusted Users](https://wiki.archlinux.org/title/Trusted_Users) and Arch Developers. Examples: Xorg, window managers, web browsers, media players, tools for working with languages such as Python and Ruby, and a lot more.
>
> (Source: https://wiki.archlinux.org/title/Official_repositories)
