### ISSUE TITLE
Old resize arrows for "original" cursor theme

### ISSUE THREAD

**Issue by Dejweed** [ful1e5/Bibata_Cursor#146]
I feel like it would be a better fit for original cursor theme to have the sharp arrows.

**Comment by Dejweed** [comment]
Oh sorry, here's what I meant:
![image](https://github.com/ful1e5/Bibata_Cursor/assets/65261588/90aceb6a-357a-468e-b92c-6b6b4bbffc5d) 
The modern resize arrows can be confusing without the context (I saw it in audacity and had no idea what it meant), so it would be nice to have classic arrows back for the original (sharp) theme.

**Comment by ful1e5** [comment]
I often receive this request. I will consider redesigning the original cursor with a sharp corner and releasing it alongside [bibata.live](https://github.com/ful1e5/bibata.live). 

Thank you for your patience.

**Comment by ful1e5** [comment]
@Dejweed  I patched cursors on the "bibata" web app. 

You can download them at https://www.bibata.live and for the development version (which I recommend until the project is in the pre-release stage) at https://dev.bibata.live/studio. 

Give it a try.

**Comment by Dejweed** [comment]
Looks good but I'm still missing pointy resize arrows (image above). Downloading involves a lot of waiting, I hope this can be improved in the future.

**Comment by Dejweed** [comment]
Nice👍

**Comment by ful1e5** [comment]
@Dejweed Updated on dev branch: https://dev.bibata.live/studio
![image](https://github.com/ful1e5/Bibata_Cursor/assets/24286590/f140151a-d5d5-408a-9777-95a24082eb72)
