### ISSUE TITLE
X11 build error

### ISSUE THREAD

**Issue by vaskark** [ful1e5/Bibata_Cursor#147]
I'm trying to build these cursors at size 16 for Linux and receive the following error:

`$ ctgen build.toml -s 16 -p x11 -d 'bitmaps/Bibata-Modern-Ice' -n 'Bibata-Modern-Ice' -c 'White and rounded egde Bibata cursors with size 16'`

> [Fail] Error occurred while processing build.toml:
> Traceback (most recent call last):
>   File "/home/vaskark/.venv/lib/python3.11/site-packages/clickgen/scripts/ctgen.py", line 156, in process
>     cfg = parse_config_file(file, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vaskark/.venv/lib/python3.11/site-packages/clickgen/configparser.py", line 190, in parse_config_file
>     config = parse_toml_file(fp, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vaskark/.venv/lib/python3.11/site-packages/clickgen/configparser.py", line 148, in parse_toml_file
>     cursors = parse_cursors_section(d, config, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vaskark/.venv/lib/python3.11/site-packages/clickgen/configparser.py", line 113, in parse_cursors_section
>     x11_blob = open_blob(blobs, hotspot, x11_sizes, x11_delay)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vaskark/.venv/lib/python3.11/site-packages/clickgen/parser/__init__.py", line 22, in open_blob
>     return parser(blob, hotspot, sizes, delay)  # type: ignore
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vaskark/.venv/lib/python3.11/site-packages/clickgen/parser/png.py", line 83, in __init__
>     super().__init__(blobs[0])
>                      ~~~~~^^^
> IndexError: list index out of range

Can someone offer some advice? I have a python venv set up (as seen) but am not an expert.
Thanks.

**Comment by ful1e5** [comment]
@vaskark 

I see that the cursor bitmaps are missing. Here are a couple of ways to fix this:

1. Install Yarn and run `yarn install`. Then, run `yarn render` (this may take around 15 minutes). Once that's done, you can run your build command.
2. If you want an easier option, download `bitmaps.zip` from the release page and unzip it in the project root directory. Then, you can run your build command without any additional steps.

**Comment by vaskark** [comment]
I tried #2 and it worked! Thanks so much for your help and for this amazing cursor set.
