### ISSUE TITLE
error Command failed with signal "SIGSEGV".

### ISSUE THREAD

**Issue by peterwu** [ful1e5/Bibata_Cursor#148]
Fedora 38 with the prerequisites installed.
Attempted to build from source of v2.0.4, or directly from main, and got error.

> $ yarn render
> yarn run v1.22.19
> $ npx cbmp render.json
> [+] Parsing Bibata-Modern-Amber Config...
> error Command failed with signal "SIGSEGV".
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by fbruetting** [comment]
@ful1e5 FYI: This makes Bibata unavailable on Fedora, sadly. 😔️

**Comment by peterwu** [comment]
@fbruetting I managed to work around this problem and the latest rpm is now available via my copr.
