### ISSUE TITLE
[Info] Android 14 is using Bibata Modern Classic mouse cursors

### ISSUE THREAD

**Issue by yochananmarqos** [ful1e5/Bibata_Cursor#151]
It seems Android 14 is now using Bibata Modern Classic cursors...

https://nitter.net/MishaalRahman/status/1666849034135384074#m

https://www.androidpolice.com/android-14-new-mouse-pointer/

@ful1e5  I wasn't sure if you knew, so I thought I'd mention it.

**Comment by ful1e5** [comment]
Updated info on https://www.bibata.live.  Thanks for your love and support.

**Comment by yochananmarqos** [comment]
FYI, Bibata Modern Classic is also preinstalled on Manjaro GNOME and Cinnamon editions. :grin:

**Comment by prithi-038** [comment]
> It seems Android 14 is now using Bibata Modern Classic cursors...
> 
> https://nitter.net/MishaalRahman/status/1666849034135384074#m
> 
> https://www.androidpolice.com/android-14-new-mouse-pointer/
> 
> [@ful1e5](https://github.com/ful1e5) I wasn't sure if you knew, so I thought I'd mention it.

this is incorrect info

**Comment by yochananmarqos** [comment]
@ful1e5 I think this issue can be closed... 😆
