### ISSUE TITLE
[feature] Cursor sizes

### ISSUE THREAD

**Issue by umarhamzy** [ful1e5/Bibata_Cursor#153]
Loving the cursor, and the work you do. Is it possible to have a cursor size between small and regular? Either options are too small or too big for me, unfortunately

**Comment by ful1e5** [comment]
@umarhamzy Thanks for your feedback! I'm glad you're enjoying the Bibata cursor.

Yes, it is possible to have a cursor size between small and regular. However, you currently need to [build Bibata from source](https://github.com/ful1e5/Bibata_Cursor#customize-sizes) to do this. I'm also developing a web app called [bibata.live](https://github.com/ful1e5/bibata.live) that will allow you to customize Bibata cursors, including the size, without having to build from source.

Here is a dev preview of Bibata Live:

https://github.com/ful1e5/Bibata_Cursor/assets/24286590/00b29980-2e36-43d2-a1ab-497c2525b1c5

**Comment by umarhamzy** [comment]
Looking forward to using bibata.live!

**Comment by umarhamzy** [comment]
@ful1e5 I've used the website, and when I tried to download size 22, It'd would present me with an error pasted below. 

`
{
    "error": [
        "Empty build directory",
        "[Errno 2] No such file or directory: '/tmp/bibata-builds/c11fcc02-817f-4901-9834-6332d277a50c/Bibata-c11fc/cursors/install.inf'"
    ],
    "id": "c11fcc02-817f-4901-9834-6332d277a50c",
    "status": 400
}
`

**Comment by ful1e5** [comment]
@umarhamzy Yes, the identical issue has been reported on https://github.com/ful1e5/bibata/issues/15. I will be incorporating the fixes shortly. As the project is presently in the alpha stage, please anticipate encountering some minor bugs. Alternatively, you may choose to wait until the stable version is officially released. 

Additionally, you have the option to access the early development version at https://dev.bibata.live.
