### ISSUE TITLE
Offline Building

### ISSUE THREAD

**Issue by D3vil0p3r** [ful1e5/Bibata_Cursor#159]
I am a NixOS user and I would like to package more customized bibata cursors.

NixOS packaging works only offline. The problem is that, when:
```
npx cbmp -d 'svg/original' -o 'bitmaps/Bibata-Gruvbox' -bc '#282828' -oc '#EBDBB2' -wc '#000000'
```
is run, `npx cbpm` command tries to connect to Internet, so the package build fails with the following error:
```
npm ERR! code EAI_AGAIN
npm ERR! syscall getaddrinfo
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/cbmp failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! Log files were not written due to an error writing to the directory: /homeless-shelter/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

error: builder for '/nix/store/dgvk6qx6npd73cjx9z3b5awgi80lp94l-bibata-cursors-2.0.3.drv' failed with exit code 1;
       last 10 log lines:
       > no configure script, doing nothing
       > Running phase: buildPhase
       > npm ERR! code EAI_AGAIN
       > npm ERR! syscall getaddrinfo
       > npm ERR! errno EAI_AGAIN
       > npm ERR! request to https://registry.npmjs.org/cbmp failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
       > 
       > npm ERR! Log files were not written due to an error writing to the directory: /homeless-shelter/.npm/_logs
       > npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
       > 
       For full logs, run 'nix log /nix/store/dgvk6qx6npd73cjx9z3b5awgi80lp94l-bibata-cursors-2.0.3.drv'.
```
Is there a way to make `cbmp` working for offline build?

If it is not possible, could you please add in this repository also all those Bibata Cursors of your [Extra](https://github.com/ful1e5/Bibata_Extra_Cursor) repository? Because by `ctgen build.toml` I can get them offline and delivering them in Nix repository.

Thank you in advance.

**Comment by ful1e5** [comment]
@D3vil0p3r No, currently it's not supported for offline builds because it relies on [puppeteer](https://pptr.dev/) internally. 

However, I'm exploring the integration of another static SVG renderer for converting static SVG files. This approach will improve render performance, especially considering the breakdown of animation frames in previous versions of Bibata. 

I'm actively working on this enhancement and plan to include it in the next release of cbmp. Thank you for your patience and understanding.

**Comment by D3vil0p3r** [comment]
This last approach could be used for building offline or it needs an Internet access?

**Comment by ful1e5** [comment]
@D3vil0p3r Offline.
