### ISSUE TITLE
icons not aligned with others

### ISSUE THREAD

**Issue by GreyXor** [ful1e5/Bibata_Cursor#161]
Hello,
`dnd_no_drop` red circle is not aligned with circles of  `dnd-link` and `dnd-copy`.
and
the bar in `zoom-in` and `zoom-out` are not the same

https://github.com/ful1e5/Bibata_Cursor/assets/79602273/418424d8-6b19-4695-bf2b-81af228a1f1e

**Comment by ful1e5** [comment]
@GreyXor I'll look into this. Thanks for reporting.
