### ISSUE TITLE
Snap Support for Modern Classic

### ISSUE THREAD

**Issue by Schildkroet** [ful1e5/Bibata_Cursor#164]
Hello,

i use Bibata Modern Classic, but it is currently not supported with Snaps. I only found Modern Ice in Snapstore.
Will there be also support for the others?

**Comment by ful1e5** [comment]
@Schildkroet Snap support isn't official. Contact the snap package maintainer to add all Bibata variants to the Snapstore.

**Comment by Gabbajoe** [comment]
@Schildkroet Hey mate I create now a snap which contains all cursors see https://snapcraft.io/bibata-all-cursor

**Comment by Schildkroet** [comment]
Thanks!
