### ISSUE TITLE
Adding chroot for EPEL 8 (copr)

### ISSUE THREAD

**Issue by jatin-cbs** [ful1e5/Bibata_Cursor#40]
Can we have that in copr the EPEL 8 repo ? All things in the repo are working in EPEL 8 I can confirm without any additional dependencies. I think it can be an easy build in copr. Thanks :) great work <3

**Comment by muhAlantabli** [comment]
@jatin-cbs On the next stable release EPEL 8 will be added.

**Comment by jatin-cbs** [comment]
@muhAlantabli thanks for the update 😉

**Comment by jatin-cbs** [comment]
Chroot is there on the EPEL page but i dont think it has any packages it just says no packages found.
