### ISSUE TITLE
Rainbow Mod(request)

### ISSUE THREAD

**Issue by ALipAkrohk** [ful1e5/Bibata_Cursor#55]
bibata could be better!.
https://store.kde.org/p/999536

**Comment by KaizIqbal** [comment]
It takes a long time to develop animation on each cursor.
Currently, I am working on the engine called [Eggy](https://github.com/KaizIqbal/eggy) that make it much easier to animate it.
I promise you you found **Bibata Rainbow** 🌈 on Eggy.
So be patient 🙂🙏

**Comment by APakrohk** [comment]
Tank's Man 👌😍

**Comment by ful1e5** [comment]
> Tank's Man ok_handheart_eyes

Take a look **Bibata Rainbow** in Action on Twitter. 
https://twitter.com/i/status/1327135956756025346

It will be released soon.
