### ISSUE TITLE
Would it be possible to have the old version as well as the new?

### ISSUE THREAD

**Issue by xircon** [ful1e5/Bibata_Cursor#58]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I like the more angular less rounded version.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dmfay** [comment]
I do like the bigger I-beam cursor but overall yeah, I'd love to see a Bibata Classic or something that preserves the sharper aesthetic.

**Comment by Stopka** [comment]
I think I can get used to new rounded style. What I do not like is too small icons behind context-menu/copy/... arrows. It is so small that it can't be recognized at all. I see only color dot. It could be the same size as in watch pointer. Also the link icon is too complicated for such a small image.
I also liked the color in zoom-in/zoom-out. On the other hand I never liked colours in window corners - the color makes no sense for me and could be just black. Not an issue, just my opinion about the desing.

**Comment by deathtrip** [comment]
I also like the sharp version better. The new rounded version feels like a totally different cursor. IMO it lost it's identity. Too similar to the many generic cursors already available. Also agree that window corners should follow the theme of the cursor, not have their own colors.

**Comment by L1pE** [comment]
On window corners, one suggestion I just thought about, they could have their color locations swapped, so the big arrow is the same as cursor color, and the "L"-shaped line is red/yellow/green/blue, so it'd be more subtle with coloration.

**Comment by JustinLovinger** [comment]
The new design doesn't feel like the same cursor. When I first updated, I genuinely thought there was an issue with my package manager, and that I was given a different cursor package.

If the author is not happy with the original Bibata Cursor design, I recommend creating a new project for this new cursor.

**Comment by Silicasandwhich** [comment]
FOR EVERYONE WHO WANTS THE OLD BIBATA: I am keeping the [bibata_cursor_translucent](github.com/silicasandwhich/bibata_cursor_translucent) cursor theme in the style of the original bibata-cursor. If you want the old bibata theme and are fine with it being ~30% less opaque, then you can use my cursor. I'm 99% sure that [bibata_adaptabreath_cursors](https://gitlab.com/cscs/Bibata_AdaptaBreath_Cursors) is doing the same thing if you're in to that color scheme, but i don't completely know if they have cursor files for Windows operating systems. I'm debating making a translucent variant of the new theme, but it will be in a new repository. I'm open to remaking the old bibata theme if enough people want it.

**Comment by deathtrip** [comment]
What do you mean by remaking the old theme?

**Comment by Silicasandwhich** [comment]
The bibata_cursor_translucent set is very similar to the original bibata_cursor. Making the old set again would require little more than changing a couple transparency values, which I could probably use a shell script to do fairly quickly.

**Comment by deathtrip** [comment]
I think it would only make sense o remake the original bibata, if you backported improvements and fixes made to the cursor and maintained the new repo. Otherwise it would just be a copy of version 0.4.1.

**Comment by Silicasandwhich** [comment]
That is true. I don't really have the time to maintain the repo to that extent, so I probably will not do that.

**Comment by KaizIqbal** [comment]
**🚀 Bibata Project** getting huge by adding colours. Everyone wants their own Bibata with minor changes likes(colour, shapes, shadows,etc..) and the process of making it's so slow (I have to change each cursor individually). Bibata contains **800+ cursors** that's a huge number for a solo developer, So I make a little bit automated in **v0.4.2**.
Currently, I am working on the **cursor engine** called **[Eggy](https://github.com/KaizIqbal/eggy)** that **automates all things** likes building, sharing, modification. You also create your own cursor theme.
I put the whole **Bibata Source** on the Eggy after it's complete.

So be Patient 🙏

**Comment by KUPOinyourWINDOW** [comment]
Sorry for dragging this back up, by all means, take as much time as you need, I just wanted to throw in my thoughts:

I prefer the old look of the cursors, the sharper aesthetic, but I do actually really like the new wait animation and the cursor for the corners and sides when you resize something. Perhaps including them in this remake could be a nice idea? A merging of the two styles, in a way.

Anyways thanks for your hard work, please keep it up!

**Comment by dmfay** [comment]
I just installed the new "original" -- it looks great, and I love the tweaks! Thanks Kaiz 🙌

**Comment by xircon** [comment]
Me too, thanks a lot :smiley:
