### ISSUE TITLE
Bibata cursor with Spotify

### ISSUE THREAD

**Issue by han190** [ful1e5/Bibata_Cursor#61]
**Describe the bug**
Hi, thanks for presenting such a nice theme for us! I have a little issue here. Whenever I move the cursor to Spotify the cursor theme changes back to Adwaita. I don't know if this is an upstream problem...

**Desktop info:**
 - OS: Fedora 31

```shell
[han@localhost ~]$ flatpak info com.spotify.Client

Spotify - Online music streaming service

          ID: com.spotify.Client
         Ref: app/com.spotify.Client/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.1.26.501
     License: LicenseRef-proprietary=https://www.spotify.com/us/legal/end-user-agreement/
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 33.8 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: e55d0e4d70691f5bb181319a15a443834c11c8ed9f018aca8744dff8f950613d
      Parent: 846948bbf9cafa09467bc881f86ffcd025c578545c652528164166d4a1681fcb
     Subject: Add workaround fixing URI opening (9c21e97e)
        Date: 2020-03-05 21:43:37 +0000
```

**Comment by KaizIqbal** [comment]
Try to edit your ```default.index``` file according to this --> https://github.com/KaizIqbal/Bibata_Cursor/issues/8#issuecomment-418274554.

**Comment by han190** [comment]
Sorry but that doesn't help. And I noticed the cursor theme in Spotify isn't Adwaita either.

**Comment by deathtrip** [comment]
It's a known issue with flatpak applications.
https://github.com/flatpak/flatpak/issues/709#issuecomment-568650898

**Comment by han190** [comment]
I happen to solve this issue through a clean install. I install bibata cursor theme first and then install spotify through flathub.
