### ISSUE TITLE
Error while running ./build.sh

### ISSUE THREAD

**Issue by Ram-Benz** [ful1e5/Bibata_Cursor#69]
Getting this error while running ./build.sh on Debian 10
```
Traceback (most recent call last):tmaps...
  File "render-cursors.py", line 52, in <module>
    from PIL import Image
ImportError: No module named PIL
 Bibata_Classic : 😔 Generating bitmaps... FAIL

 Aborting...

```

Is this due to snap pakages installed? If yes , is there in workaround for this ?

**Comment by KaizIqbal** [comment]
This error is *caused* by [Pillow](https://pypi.org/project/Pillow/) (A Image processing library). 
Sounds like **pillow** is **not installed** on your system, **Pillow** is `python package` so make sure *python* or *python3* already installed on a system. 

📝 **Note**: I recommend `python3`  for ***build***.

To install **python3**
```
$ sudo apt update && sudo apt install python3 python3-pip
```

To install  **Pillow**

```bash
$ pip3 install pillow           # for python3
 
$ pip install pillow             # for python2
```

Also, Check other **build dependencies** [here](https://github.com/KaizIqbal/Bibata_Cursor#build-dependencies)
