### ISSUE TITLE
Re: #50: Pip requirement is back

### ISSUE THREAD

**Issue by yochananmarqos** [ful1e5/Bibata_Cursor#74]
See https://github.com/ful1e5/Bibata_Cursor/issues/50#issuecomment-568239188

I'm the Co-Maintainer of the [`bibata-cursor-theme`](https://aur.archlinux.org/packages/bibata-cursor-theme/) AUR package. With 1.0.0, it will not build without Pip since it's called in the `setup.py`. The Python requirements are met with [`python-clickgen`](https://aur.archlinux.org/packages/python-clickgen/).

P.S. Your bug report template is awkward.

**Comment by Tamas-Toth-ebola** [comment]
Hi! I'm thinking I had got something same like on Ubuntu 20.04 with current 1.0.0 release:

![image](https://user-images.githubusercontent.com/25765137/95322885-83db3100-089d-11eb-9696-1f83d8f3fb65.png)

**Comment by yochananmarqos** [comment]
@Tamas-Toth-ebola Your error is not related to this issue. It's complaining it can't find the Pillow module, which is odd because it detected Pillow is installed.

**Comment by Tamas-Toth-ebola** [comment]
Yes! This is why I sent it. Could I report it as discrete bug? Or could I send any other environmental info?

**Comment by yochananmarqos** [comment]
@Tamas-Toth-ebola Please create your own issue as it has nothing to do with this one. Please also delete your posts here after.

**Comment by ful1e5** [comment]
> Hi! I'm thinking I had got something same like on Ubuntu 20.04 with current 1.0.0 release:
> 
> ![image](https://user-images.githubusercontent.com/25765137/95322885-83db3100-089d-11eb-9696-1f83d8f3fb65.png)

I notice that you are on **wrong** **branch**. From v1.0.0 **default** branch is `main`.
```bash
git checkout main
git pull
```
check build docs here :point_down: 
https://github.com/ful1e5/Bibata_Cursor#manual-build

**Comment by Tamas-Toth-ebola** [comment]
Thank you! Absolutely true! This was a major problem, sorry for your time. I cloned the repo long time ago, do not remember why I was on master instead of main. Problem solved!

**Comment by ful1e5** [comment]
> See [#50 (comment)](https://github.com/ful1e5/Bibata_Cursor/issues/50#issuecomment-568239188)
> 
> I'm the Co-Maintainer of the [`bibata-cursor-theme`](https://aur.archlinux.org/packages/bibata-cursor-theme/) AUR package. With 1.0.0, it will not build without Pip since it's called in the `setup.py`. The Python requirements are met with [`python-clickgen`](https://aur.archlinux.org/packages/python-clickgen/).
> 
> P.S. Your bug report template is awkward.

Just pushed a new **build process** on [dev_tree](https://github.com/ful1e5/Bibata_Cursor/tree/dev) with `setup.py`. 

### Updated `build` Commands
#### Install `builder`:
```bash
python setup.py install
```

#### Build Windows & X11 cursors:
```bash
python build.py
```

#### Build `x11` cursor only:
```bash
python build.py --x11
```

#### Build `Windows` cursor only:
```bash
python build.py --win
```
