### ISSUE TITLE
Fails to build in clean chroot

### ISSUE THREAD

**Issue by yochananmarqos** [ful1e5/Bibata_Cursor#75]
AUR package Co-Maintainer here. I can build just fine normally, however it fails in a clean chroot. Even adding `gtk3` as a build dependency, the browser process still fails. I imagine it has something to do with `puppeteer`. Why is that necessary to render icons? A browser process? 

```
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 23.54s.
yarn run v1.22.5
$ yarn workspace bibata-modern render
$ yarn build && node dist/index.js
$ npx tsc --build
-  Preparing Bibata-Modern-Amber .svg files...
Error: Failed to launch the browser process!
/build/bibata-cursor-theme/src/Bibata_Cursor-1.0.0/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/build/bibata-cursor-theme/src/Bibata_Cursor-1.0.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/build/bibata-cursor-theme/src/Bibata_Cursor-1.0.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Done in 5.62s.
yarn run v1.22.5
$ yarn workspace bibata-original render
$ yarn build && node dist/index.js
$ npx tsc --build
-  Preparing Bibata-Original-Amber .svg files...
Error: Failed to launch the browser process!
/build/bibata-cursor-theme/src/Bibata_Cursor-1.0.0/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/build/bibata-cursor-theme/src/Bibata_Cursor-1.0.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/build/bibata-cursor-theme/src/Bibata_Cursor-1.0.0/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Done in 4.03s.
yarn run v1.22.5
$ rm -rf themes && python build.py
⚡ Bibata Builder Version 1.0.0
🌈 Building Bibata-Modern-Amber Theme ...
🚨 No configs found in /tmp/tmp3inx0a9o
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ful1e5** [comment]
### Why Bibata using `puppeteer`?

`puppeteer` is a headless browser based on **Chromium**. Browsers are the best `.svg` file render with `.svg` animation using **CSS**, **SMIL**(Synchronized Multimedia Integration Language).`puppeteer` in `bibata-core` just taking **screenshots** of SVG file and saving as `.png`.

### `PKGBUILD` 

#### Problem

```diff
- /build/bibata-cursor-theme/src/Bibata_Cursor-1.0.0/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

#### Solution

`nss` package is not installed on the system that's required in google-chrome.

#### Try these `depends` in PKGBUILD

```
depends=('alsa-lib' 'gtk3' 'libcups' 'libxss' 'libxtst' 'nss' 'python-clickgen' 'yarn' 'npm')
```

I'm running `Manjaro 20.1.1` with **[aur:google-chrome](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=google-chrome)** installed, And current `PKGBUILD`(1.0.0-1) works for me.

![bibata-aur-installed](https://imgur.com/U5aTHWP.png)

**Comment by deathtrip** [comment]
I have all the above dependencies installed and also get an error:
> ⠸  Preparing Bibata-Modern-Amber .svg files...Error: Failed to launch the browser process!
[1004/122929.416469:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

**Comment by ful1e5** [comment]
> I have all the above dependencies installed and also get an error:
> 
> > ⠸  Preparing Bibata-Modern-Amber .svg files...Error: Failed to launch the browser process!
> > [1004/122929.416469:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
> 
> I use Arch with Chromium installed.

Here is a workaround for **Chromium**
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox

**Comment by yochananmarqos** [comment]
@ful1e5 That can't be done during build as `chown root:root` will fail. `sudo` cannot be used and the fakeroot environment is only in the package() function.

**Comment by ful1e5** [comment]
@yochananmarqos 

### update `PKGBUILD`
```
pkgname=bibata-cursor-theme
pkgver=1.0.0
pkgrel=2
pkgdesc="Material Based Cursors"
arch=('any')
url="https://github.com/ful1e5/Bibata_Cursor"
license=('GPL3')
makedepends=('python-clickgen' 'curl' 'unzip')
options=('!strip')
source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz")
sha256sums=('5e694dafa6d0a338bb744d43d09b0d31fc55f105b3659754ea226d170b590999')

prepare() {
  cd "$srcdir/Bibata_Cursor-$pkgver"
   
  # Downloading cursors bitmaps
  curl -LO "https://github.com/ful1e5/Bibata_Cursor/releases/download/v$pkgver/bitmaps.zip"
  
  # Unziping bitmaps.zip   
  mkdir -p bitmaps
  unzip bitmaps.zip -d bitmaps
}

build() {
  cd "$srcdir/Bibata_Cursor-$pkgver"
  
  # Building Cursors   
  rm -rf themes
  python build.py
}

package() {
  cd "$srcdir/Bibata_Cursor-$pkgver"
  install -d "$pkgdir/usr/share/icons"
  cp -r themes/Bibata-* "$pkgdir/usr/share/icons"
  chmod -R 755 "$pkgdir"/usr/share/icons/Bibata-*
}
```

**Comment by yochananmarqos** [comment]
The package is a little larger, but it works. Thanks. Update is pushed.

```
Packages (1) bibata-cursor-theme-1.0.0-2

Total Installed Size:  176.47 MiB
Net Upgrade Size:        2.20 MiB
```

**Comment by ful1e5** [comment]
> The package is a little larger, but it works. Thanks. Update is pushed.
> 
> ```
> Packages (1) bibata-cursor-theme-1.0.0-2
> 
> Total Installed Size:  176.47 MiB
> Net Upgrade Size:        2.20 MiB
> ```

Package size is reduced by removing ***-Windows** cursors.

**Comment by yochananmarqos** [comment]
Ah, forgot to remove the Windows cursors.

That wasn't the point, though. The previous package build with Yarn also had the Windows cursors in it. No big deal, was just an observation.

**Comment by yochananmarqos** [comment]
@ful1e5 Since you implemented a working solution, you could probably unpin this and close it. :wink:
