### ISSUE TITLE
Wrong Implemetation [Resize Cursors]

### ISSUE THREAD

**Issue by ful1e5** [ful1e5/Bibata_Cursor#76]
## Description of the problem
Some cursors had wrong implementation in **Bibata-Modern** & **Bibata-Original**

#### Cursors 
- `bd_double_arrow` 
- `fd_double_arrow`

## How has this issue affected you? What are you trying to accomplish?
Discover wrong cursors when I taking `selection` screenshot in **Spectacle**(KDE screenshot utility).

### Logs or Screenshots: (optional)
![bug](https://i.imgur.com/GF0fkid.gif)
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Operating System |          Manjaro 20.1.1    |

**Comment by Neur1n** [comment]
Now the problem is on Windows side. Hilarious.

**Comment by AllizomFoxfire** [comment]
It's an easy fix in Windows. I just switched the file names referenced in "dgn1" and  "dgn2" in the install.inf file for all 3 versions. worked like a charm.

Of course, those less savvy would have no idea what an inf file is or how to modify it, so a patch would be best. 

No humblebrag intended. Seriously.

**Comment by Neur1n** [comment]
@AllizomFoxfire I've fixed it by using the `Mouse Properties` instead, but it is still an issue that affects people. I should have mentioned the work-around as you do.

**Comment by AllizomFoxfire** [comment]
@Neur1n TBH, that is the quickest way to fix it for sure and I probably should have just done it that way. It's the engineer in me that always tries to fix the root problem instead of just going for a quick fix.

As it's just for me, I should have just done your solution, but it didn't come to mind.

**Comment by gilbertohasnofb** [comment]
The size of the cursors on Windows all look huge. They seem to be 32 pixels instead of the 24 pixels used in Linux Mint. Is there a way of tweaking their size?

**Comment by AllizomFoxfire** [comment]
Personally, that is the reason I chose them.  As I have to cast my desktop
across the room to a 65" TV daily, these cursors have high visibility and
are pleasing to the eye.

As to your question, the cursor images would have to be modified by the
artist.

Thanks,

Shawn Egan
