### ISSUE TITLE
spinning wheel border size in amber variants

### ISSUE THREAD

**Issue by deathtrip** [ful1e5/Bibata_Cursor#78]
## Description of the problem
The border size of the big and small spinning wheels, in amber variants of bibata modern and classic, is too large.

## How has this issue affected you? What are you trying to accomplish?
Get the border size same as the other variants.
### Logs or Screenshots: (optional)
Here you can see the big and small wheels vs bibata original:

![border](https://user-images.githubusercontent.com/8403455/96297438-23f92e80-0ff1-11eb-9c3c-aee9639567bc.jpg)

### Your Environment
Linux KDE

**Comment by ful1e5** [comment]
Thanks, @deathtrip  for **reporting**. I will cosidering this in new release. 😌
Can you suggest a colour that contrast with **Amber & Spining-Wheel**?

### Colour suggestion
![Amber](https://i.imgur.com/11IekAD.png)

check [original/color.ts](https://github.com/ful1e5/Bibata_Cursor/blob/main/packages/modern/src/colors.ts) for more colours info.

**Comment by deathtrip** [comment]
I assume you mean the outline of the wheel that is now white, and is black in bibata original.
Hard to find a suitable color except white. Maybe replace the orange in the wheel with red and make the outline the same as the main color of the cursor - orange, just like in the black variant there's an black outline.

**Comment by ful1e5** [comment]
@deathtrip  I end up with **Rich Black** in `watch` background. This colour work well with **Bibata Amber**. 
Colour palette on **[coolors.co](https://coolors.co/ff8300-001524)**

![Bibata Amber upcoming chnage](https://imgur.com/XaRd6cQ.png)
