### ISSUE TITLE
Is it possible to have even more sizes?

### ISSUE THREAD

**Issue by areographe** [ful1e5/Bibata_Cursor#80]
Hey, thanks for covering such a great range of cursor sizes with this theme. I was wondering if it's possible to generate even smaller sizes, for my low-resolution laptop screen? Even the 22px size seems a bit too big - would it be possible to create a 20px or 18px version?

**Comment by ful1e5** [comment]
Yup. You can change cursor size as you wish like **[this](https://github.com/ful1e5/Bibata_Cursor/commit/873cbb31aadccbb2c61ab5b9a94583e191c109a8)**.

### Work arround for generating 18 & 20 cursor size
0. Pepare
```
$ git checkout main
$ git pull
``` 

1. Change `sizes` variable in [builder/config.py](https://github.com/ful1e5/Bibata_Cursor/blob/main/builder/config.py)
```diff
...
- sizes = [22, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
+ sizes = [18, 20]
...
```
2. Download latest **bitmaps** (that skips `yarn render:*` commands)
```
$ curl -L -o bitmaps.zip https://github.com/ful1e5/Bibata_Cursor/releases/download/v1.0.2/bitmaps.zip 
```
3. Extract **bitmaps.zip**
```
$ rm -rf bitmaps && mkdir bitmaps
$ unzip bitmaps.zip -d bitmaps
```
4. Build
```
$ pip3 install clickgen
$ python3 setup.py install
$ python3 build.py
```
5. **[Install](https://github.com/ful1e5/Bibata_Cursor#install-build-theme)** theme.

**Comment by areographe** [comment]
Thanks so much, this worked perfectly :)
