### ISSUE TITLE
Bibata Modern Rainbow for Windows!

### ISSUE THREAD

**Issue by ferminmine** [ful1e5/Bibata_Cursor#90]
Hi! I wanted to ask for support for Windows.

Honestly I don't have much experience working with cursor or OS libraries, but I tested the family of Bibata Rainbow on KDE and it is by far the best cursor family I've ever seen and I thought it'd be awesome if the Rainbow family of Bibata would be ported to Windows.
I see that only the Bibata Original is supported on Windows in the release 1.0.0

Thanks for reading!

**Comment by ful1e5** [comment]
Bibata Rainbow v1.1.0 is now supported on Windows. You could download binaries on [pling.com](https://www.pling.com/p/1445634/) or [release page](https://github.com/ful1e5/Bibata_Cursor_Rainbow/releases).
If you have any issues or problems related to Bibata Rainbow, Let me know on [Bibata_Cursor_Rainbow/issue](https://github.com/ful1e5/Bibata_Cursor_Rainbow/issues).
