### ISSUE TITLE
How to build from scrach

### ISSUE THREAD

**Issue by Neur1n** [ful1e5/Bibata_Cursor#99]
## Description of the problem
I'm trying to build Bibata from scratch in order to have different cursor size than the default one, using WSL2 (Ubuntu 20.04) on Windows 10. But neither running `make` nor `python3 build.py` works.

## How has this issue affected you? What are you trying to accomplish?
I couldn't finish the build.

### Logs or Screenshots: (optional)
![image](https://user-images.githubusercontent.com/17579247/115698282-07222700-a397-11eb-80d3-499bd02adc32.png)
![image](https://user-images.githubusercontent.com/17579247/115698526-4a7c9580-a397-11eb-9efd-28670d5c3d31.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| WSL 2 | Ubuntu 20.04          |

Thanks.

**Comment by ful1e5** [comment]
Bibata builder raising `FIleNotFoundError` exception for bitmaps. First, you need bitmaps for building Bibata from the ground up. You should generate bitmaps from `.svg` files. For that, you should have node.js & yarn installed on the WSL system or you should skip this step by downloading the latest `bitmaps.zip` archive from the GitHub Release page. Here are both build procedures.

> Make sure you are in the project root before building bibata.

### Build From Scratch

#### Build & Customize `Unix Cursors Only
```bash
make unix X_SIZES=22 24 32      # Multiple sizes are provided with  ' '(Space)
```
#### Build & Customize `Windows` Cursors Only
```bash
make windows WIN_SIZE=48
```

### Build with Skip method (recommended)

#### Preparation 
```bash
# Download the latest bitmaps.zip 
curl -L -o bitmaps.zip https://github.com/ful1e5/Bibata_Cursor/releases/download/v1.1.1/bitmaps.zip

# extract archive
rm -rf bitmaps && unzip bitmaps.zip -d bitmaps
```

#### build & customize for `Unix` Only
```bash
cd builder
make build_unix X_SIZES=22 24 32      # Multiple sizes are provided with  ' '(Space)
```

#### build & customize for `Windows` Only
```bash
cd builder
make build_windows WIN_SIZE=48
```

After executing these commands  `themes` directory would be created at the project root. If Bibata builder raises any `symlink` exception, Remove the `themes` directory from the project root and give it a try again.

**Comment by Neur1n** [comment]
It works! Thanks a lot!
